### ISSUE TITLE
Unable to change password in EXANode user interface

### ISSUE THREAD

**Issue by Pcolar** [dpn-admin/EXANode-Acceptance-testing#2]
https://exanode-demo.libnova.com/user

When attempting to change a user's password, as an administrator, the system returns

Form error:

**Comment by acarrasco-libnova** [comment]
This issue was due how we generate update packages for the demo instance.

We were skipping the framework configuration files, as they use to have custom settings for each system, as the base url, the database settings, filesystem directories...

The form validation configuration file was outdated as of this, and that caused the issue.

We've updated the package generator script, and should include now specific configuration files that don't conflict with the environment. The latest package has been applied to the demo instance and should be working fine now.

**Comment by Pcolar** [comment]
Please do not close issues until the result has been validated!

**Comment by Pcolar** [comment]
Password change is validated.
