### ISSUE TITLE
3.3.4.8. MBR.003.002 Deposit details - “Error” (MBR.003.002.D)

### ISSUE THREAD

**Issue by Pcolar** [dpn-admin/EXANode-Acceptance-testing#21]
Please demonstrate this status:

If the status is “Error” (MBR.003.002.D), it shows a message indicating that the DPN team is working on it.

**Comment by Pcolar** [comment]
Under what conditions is this generated?
Can this error notification be generated by test data?

**Comment by acarrasco-libnova** [comment]
This happens when any of the LIBSAFE modules find any error while processing the content of a deposit, or when a system error happens while processing the deposit.

We don't have any sort of data to force the modules to fail, however, you can create a deposit with the transfer method "FTPS", transfer the content, switch back to "Trusty", and try to preserve it. As it will expect the integrity manifest, it will fail.

**Comment by Pcolar** [comment]
Failure scenario is verified.
What are the recovery options for this failure case?

**Comment by acarrasco-libnova** [comment]
This specific error has been triggered manually by an action that a normal user of the platform should not be able to perform, but it was intended to show you how the system handles these kind of situations, so you can see an alert triggered by the actual system and not hand-crafted, which does not demonstrate that the system is working.

The modules have routines to handle most common errors and avoid the need of any sort of intervention, but if a notification is sent about an error over the content of any deposit, it will surely be a critical error and **will require manual intervention**.

However, any failed deposit can be issued back to their previous state as a System administrator using the web interface, with the button "Retry" at the bottom of the deposit details view. It will make the process that failed to take place again, which is useful in scenarios where the failure has happened due to a failure in an external component that was unavailable due to external reasons (Isilon not available due to a machine shutdown for update) or to restart the processes once the problems have been fixed.

![image](https://user-images.githubusercontent.com/36916975/42836972-e6325846-89fc-11e8-9bda-cfe1c2224120.png)

**Comment by Pcolar** [comment]
Thanks for the clarification!
